import React, { useEffect, useState } from "react";
import { api, setConfig, testConnection } from "./lib/api";

type Page = "conversation"|"dashboard"|"runs"|"providers"|"inspector"|"workspace"|"settings"|"approvals";
const pages: Page[] = ["conversation","dashboard","runs","providers","inspector","workspace","approvals","settings"];
const style: Record<string, React.CSSProperties> = {
  app:{display:"flex",height:"100vh",background:"#0d1117",color:"#d8dee9",fontFamily:"system-ui"}, nav:{width:190,padding:16,borderRight:"1px solid #30363d"}, main:{flex:1,padding:20,overflow:"auto"}, card:{border:"1px solid #30363d",borderRadius:8,padding:16,marginBottom:12,background:"#161b22"}, input:{width:"100%",boxSizing:"border-box",padding:10,background:"#0d1117",color:"#d8dee9",border:"1px solid #30363d",borderRadius:6}, button:{padding:"8px 12px",background:"#2563a6",color:"white",border:0,borderRadius:6,cursor:"pointer"}
};
export default function App(){
 const [page,setPage]=useState<Page>("dashboard"), [connected,setConnected]=useState(false), [data,setData]=useState<any>({}), [error,setError]=useState("");
 useEffect(()=>{void testConnection().then(setConnected);},[]);
 async function load(){ try { const route:Record<Page,string>={conversation:"/api/runtime/sessions",dashboard:"/api/runtime/dashboard",runs:"/api/runtime/runs",providers:"/api/v1/providers",inspector:"/api/inspector/runtime",workspace:"/api/workspace",settings:"/api/v1/status",approvals:"/api/control/approvals"}; setData(await api(route[page])); setError(""); } catch(e){setError(String(e));} }
 useEffect(()=>{if(connected) load();},[page,connected]);
 if(!connected) return <Connect onReady={()=>setConnected(true)}/>;
 return <div style={style.app}><nav style={style.nav}><h2>NOUS</h2>{pages.map(item=><button key={item} style={{...style.button,width:"100%",marginBottom:6,background:item===page?"#2563a6":"transparent",textAlign:"left"}} onClick={()=>setPage(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</nav><main style={style.main}><h1>{page[0].toUpperCase()+page.slice(1)}</h1>{error&&<p>{error}</p>}{page==="conversation"?<Conversation/>:page==="approvals"?<Approvals data={data} refresh={load}/>:<Panel data={data}/>}</main></div>;
}
function Connect({onReady}:{onReady:()=>void}){const [url,setUrl]=useState("http://localhost:8770"),[token,setToken]=useState(""),[status,setStatus]=useState(""); return <div style={{...style.app,alignItems:"center",justifyContent:"center"}}><div style={{...style.card,width:420}}><h2>Connect to Nous Runtime</h2><input style={style.input} value={url} onChange={e=>setUrl(e.target.value)}/><input style={{...style.input,marginTop:8}} type="password" placeholder="Runtime token" value={token} onChange={e=>setToken(e.target.value)}/><button style={{...style.button,marginTop:12}} onClick={async()=>{setConfig({url,token}); const ok=await testConnection(); setStatus(ok?"Connected":"Connection failed"); if(ok)onReady();}}>Connect</button><p>{status}</p></div></div>}
function Panel({data}:{data:any}){return <pre style={{...style.card,whiteSpace:"pre-wrap"}}>{JSON.stringify(data,null,2)}</pre>}
function Conversation(){const [message,setMessage]=useState(""),[result,setResult]=useState(""); return <div style={style.card}><textarea style={style.input} rows={5} value={message} onChange={e=>setMessage(e.target.value)}/><button style={{...style.button,marginTop:8}} onClick={async()=>setResult(JSON.stringify(await api("/api/chat",{method:"POST",body:JSON.stringify({text:message})}),null,2))}>Send</button><pre>{result}</pre></div>}
function Approvals({data,refresh}:{data:any,refresh:()=>void}){const items=data.approvals||data||[]; return <div>{Array.isArray(items)&&items.map((item:any)=><div style={style.card} key={item.request_id||item.id}><strong>{item.summary||item.action}</strong><p>{item.risk_summary}</p><button style={style.button} onClick={async()=>{await api("/api/ide/runtime",{method:"POST",body:JSON.stringify({action:"approval.resolve",params:{request_id:item.request_id||item.id,decision:"approve"}})});refresh();}}>Approve once</button><button style={{...style.button,marginLeft:8,background:"#8b3030"}} onClick={async()=>{await api("/api/ide/runtime",{method:"POST",body:JSON.stringify({action:"approval.resolve",params:{request_id:item.request_id||item.id,decision:"reject"}})});refresh();}}>Reject</button></div>)}</div>}
